language: node_js
node_js:
- "stable"

directories:
  - "node_modules"
script:
  - npm run test
  - sbt coveralls
after_script:
- ./node_modules/.bin/mocha ./test/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js